version: '3.8'

services:
  catfishapiagg:
    build: .
    container_name: catfishapiagg_service

    ports:
      - "${PORT}:${PORT}"

    volumes:
      # 数据直接落到 docker-compose.yml 所在目录的 data 文件夹
      - ./data:/app/data

    environment:
      - ADMIN_KEY=${ADMIN_KEY}
      - PORT=${PORT}

    restart: unless-stopped
